import type { Metadata } from "next";
import { inter }  from "@/app/font";
import "./globals.css";
import Header from "../components/Header";
import { MessageContainer } from "@/components/ui/message";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <MessageContainer />
        <Header />
        <main className="mt-4" style={{ height: 'calc(100vh - 56px)'}}>
          {children}
        </main>
      </body>
    </html>
  );
}

